export const initialPosts = [
    {
        id: 1,
        author: 'John Doe',
        avatar: 'https://via.placeholder.com/50',
        date: new Date(),
        content: 'This is a sample post content here i am writen it only for testing purpose.',
        image: 'https://via.placeholder.com/300',
        likes: [899, 9809, 909],
        userId: 8888888,
        comments: ['Nice post!', 'Thanks for sharing.'],
    },
    {
        id: 2,
        author: 'John Doe',
        avatar: 'https://via.placeholder.com/50',
        date: new Date(),
        content: 'This is a sample post content here i am writen it only for testing purpose.',
        image: 'https://via.placeholder.com/300',
        likes: [899, 9809, 909, 90],
        userId: 8888888,
        comments: ['Nice post!', 'Thanks for sharing.'],
    },
    {
        id: 3,
        author: 'John Doe',
        avatar: 'https://via.placeholder.com/50',
        date: new Date(),
        content: 'This is a sample post content here i am writen it only for testing purpose.',
        image: 'https://via.placeholder.com/300',
        likes: [5],
        userId: 9050778575,
        comments: ['Nice post!', 'Thanks for sharing.'],
    },
    // Add more initial posts here
];